# Default language if you have a multi-language setup
DefaultContentLanguage = "en"

baseURL = "https://anssipiirainen.com"

theme = "amperage"

pygmentsUseClasses = true

IsMultiLingual = false

# Number of posts shown per page (dafault: 10)
paginate = 10

# Language sections
[languages]
    [languages.en]
        contentDir = "content"
        languageName = "English"
        languageCode = "en"
        title = "Anssi Piirainen"
        description = "Porsonal blog b"
        weight = 1

# Enable only tags taxonomy
[taxonomies]
    tag = "tags"

[params]
    copyright = "Anssi Piirainen" # Name shown on footer copyright
    themeColor = "#333" # Theme color displayed on mobile browsers

    # Default AMP components for the whole site
    ampElements = ["amp-iframe", "amp-analytics", "amp-social-share", "amp-install-serviceworker"]

    # Google Analytics code
    # googleAnalytics = "UA-xxxxxxxxx-x"

    # Adsense publisher code
    # adsensePublisher = "ca-pub-123456789"

    # Comments Iframe URL
    # commentsEmbedUrl = "https://comments.example.com"

    # Social sites for metatags
    facebookSite = "example"
    twitterSite = "@example"

    # Structured data elements
    socialProfiles = ["https://twitter.com/example","https://www.linkedin.com/in/example/","https://github.com/example"]

    alternatePageName = "Anssi Piirainen"
    organizationLogo = "/logo.png"
    organizationName = "Northern Peaks Development"

    publisherName = "anssi"
    publisherLogo = "/logo-amp-article.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60

[markup]
    defaultMarkdownHandler = "blackfriday"
