# Default language if you have a multi-language setup
DefaultContentLanguage = "en"

baseURL = "https://anssipiirainen.com"

theme = "amperage"

pygmentsUseClasses = true

IsMultiLingual = false

enableEmoji = true

# Number of posts shown per page (dafault: 10)
paginate = 10

# Language sections
[languages]
    [languages.en]
        contentDir = "content"
        languageName = "English"
        languageCode = "en"
        title = "Anssi Piirainen"
        description = "Personal blog by Anssi Piirainen, a software engineering professional from Finland."
        weight = 1

# Enable only tags taxonomy
[taxonomies]
    tag = "tags"

[params]
    copyright = "Anssi Piirainen" # Name shown on footer copyright
    themeColor = "#333" # Theme color displayed on mobile browsers

    # Default AMP components for the whole site
#    ampElements = ["amp-iframe", "amp-analytics", "amp-social-share", "amp-install-serviceworker"]

    # Adsense publisher code
    # adsensePublisher = "ca-pub-123456789"

    # Comments Iframe URL
    # commentsEmbedUrl = "https://comments.example.com"

    # Social sites for metatags
    facebookSite = "anssipiirainen.com"
    twitterSite = "anssipiirainen.com"

    # Structured data elements
    socialProfiles = ["https://twitter.com/example","https://www.linkedin.com/in/example/","https://github.com/example"]

    alternatePageName = "Anssi Piirainen"
    organizationLogo = "/logo.png"
    organizationName = "Northern Peaks Development"

    publisherName = "anssi"
    publisherLogo = "/logo-amp-article.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60

[markup]
    defaultMarkdownHandler = "goldmark"

[deployment]
    # By default, files are uploaded in an arbitrary order.
    # Files that match the regular expressions in the "Order" list
    # will be uploaded first, in the listed order.
    order = [".jpg$", ".gif$"]


[[deployment.targets]]
    # An arbitrary name for this target.
    name = "s3"
    # The Go Cloud Development Kit URL to deploy to. Examples:
    # GCS; see https://gocloud.dev/howto/blob/#gcs
    # URL = "gs://<Bucket Name>"

    # S3; see https://gocloud.dev/howto/blob/#s3
    # For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
    URL = "s3://anssipiirainen.com?region=eu-north-1"

    # Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
    # URL = "azblob://$web"

    # You can use a "prefix=" query parameter to target a subfolder of the bucket:
    # URL = "gs://<Bucket Name>?prefix=a/subfolder/"

    # If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
    cloudFrontDistributionID = "E2JG02Z9MUOUYM"

# Optionally, you can include or exclude specific files.
# See https://godoc.org/github.com/gobwas/glob#Glob for the glob pattern syntax.
# If non-empty, the pattern is matched against the local path.
# All paths are matched against in their filepath.ToSlash form.
# If exclude is non-empty, and a local or remote file's path matches it, that file is not synced.
# If include is non-empty, and a local or remote file's path does not match it, that file is not synced.
# As a result, local files that don't pass the include/exclude filters are not uploaded to remote,
# and remote files that don't pass the include/exclude filters are not deleted.
# include = "**.html" # would only include files with ".html" suffix
# exclude = "**.{jpg, png}" # would exclude files with ".jpg" or ".png" suffix


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:

[[deployment.matchers]]
    #  Cache static assets for 1 year.
    pattern = "^.+\\.(js|css|svg|ttf)$"
    cacheControl = "max-age=31536000, no-transform, public"
    gzip = true

[[deployment.matchers]]
    pattern = "^.+\\.(png|jpg)$"
    cacheControl = "max-age=31536000, no-transform, public"
    gzip = false

[[deployment.matchers]]
    pattern = "^.+\\.(html|xml|json)$"
    gzip = true
